name: Deploy Theme and WordPress Pages

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Theme and WordPress Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Add steps for transferring theme files
      - name: Transfer Theme Files to Staging Server
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/html/wordpress/wp-content/themes/project-team9"
          SCRIPT_BEFORE: ls
      
      # Add steps for exporting WordPress pages
      - name: Export WordPress Pages
        run: |
          wp export --path=/var/www/html/wordpress --post_type=page --post_status=publish --stdout > wordpress_pages.xml

      # Add steps for transferring WordPress pages to the staging server
      - name: Transfer WordPress Pages to Staging Server
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./wordpress_pages.xml"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/html/wordpress"
          SCRIPT_BEFORE: |
            mv wordpress_pages.xml /var/www/html/wordpress
