name: Deploy Theme and WordPress Pages

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Theme and WordPress Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install PHP and related dependencies
      - name: Install PHP
        run: sudo apt-get install php php-cli

      # Install WP-CLI
      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      # Export WordPress pages locally
      - name: Export WordPress Pages
        run: |
          wp export --path=/var/www/html/wordpress --post_type=page --post_status=publish --stdout > wordpress_pages.xml

      # Transfer Theme Files to Staging Server
      - name: Transfer Theme Files to Staging Server
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/html/wordpress/wp-content/themes/project-team9"
          SCRIPT_BEFORE: ls
      
      # Transfer WordPress Pages to Staging Server
      - name: Transfer WordPress Pages to Staging Server
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./wordpress_pages.xml"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/html/wordpress"
          SCRIPT_BEFORE: |
            mv wordpress_pages.xml /var/www/html/wordpress
