name: Deploy Theme

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Theme
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20

    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/html/wordpress/wp-content/themes"
