name: Deploy Theme

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Theme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: "-rlgoDzvc -i"
          path: "./"
          remote_path: "/var/www/html/wordpress/wp-content/themes"
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
